-- 0003_reference_data.sql — the dial plan behind the rule picker.
--
-- This table is a convenience, not a dependency. Matching in domain/phone.ts
-- works on raw digits and never consults it: a subscriber can enter a prefix
-- that is not listed here and it will filter correctly. What the table buys is
-- a searchable list in the dashboard and a human label on each rule and each
-- activity row, so "234" reads as "Nigeria" a month later.
--
-- Labels are advisory. NANP area codes in particular are reassigned and split
-- over time; a stale label mislabels a picker entry and changes no decision.

set search_path = public;

create type dial_prefix_kind as enum ('country', 'nanp_area');

create table dial_prefixes (
  prefix text primary key check (prefix ~ '^[1-9][0-9]{0,14}$'),
  kind   dial_prefix_kind not null,
  name   text not null,
  -- Two-letter region for grouping in the picker; ISO country code where there
  -- is one, else the NANP territory the area code sits in.
  region text
);
create index dial_prefixes_kind_idx on dial_prefixes(kind);

grant select on dial_prefixes to anon, authenticated, service_role;

-- ---------------------------------------------------------------- country codes

insert into dial_prefixes (prefix, kind, name, region) values
  ('7','country','Russia / Kazakhstan','RU'),
  ('20','country','Egypt','EG'),
  ('27','country','South Africa','ZA'),
  ('30','country','Greece','GR'),
  ('31','country','Netherlands','NL'),
  ('32','country','Belgium','BE'),
  ('33','country','France','FR'),
  ('34','country','Spain','ES'),
  ('36','country','Hungary','HU'),
  ('39','country','Italy','IT'),
  ('40','country','Romania','RO'),
  ('41','country','Switzerland','CH'),
  ('43','country','Austria','AT'),
  ('44','country','United Kingdom','GB'),
  ('45','country','Denmark','DK'),
  ('46','country','Sweden','SE'),
  ('47','country','Norway','NO'),
  ('48','country','Poland','PL'),
  ('49','country','Germany','DE'),
  ('51','country','Peru','PE'),
  ('52','country','Mexico','MX'),
  ('53','country','Cuba','CU'),
  ('54','country','Argentina','AR'),
  ('55','country','Brazil','BR'),
  ('56','country','Chile','CL'),
  ('57','country','Colombia','CO'),
  ('58','country','Venezuela','VE'),
  ('60','country','Malaysia','MY'),
  ('61','country','Australia','AU'),
  ('62','country','Indonesia','ID'),
  ('63','country','Philippines','PH'),
  ('64','country','New Zealand','NZ'),
  ('65','country','Singapore','SG'),
  ('66','country','Thailand','TH'),
  ('81','country','Japan','JP'),
  ('82','country','South Korea','KR'),
  ('84','country','Vietnam','VN'),
  ('86','country','China','CN'),
  ('90','country','Turkey','TR'),
  ('91','country','India','IN'),
  ('92','country','Pakistan','PK'),
  ('93','country','Afghanistan','AF'),
  ('94','country','Sri Lanka','LK'),
  ('95','country','Myanmar','MM'),
  ('98','country','Iran','IR'),
  ('211','country','South Sudan','SS'),
  ('212','country','Morocco','MA'),
  ('213','country','Algeria','DZ'),
  ('216','country','Tunisia','TN'),
  ('218','country','Libya','LY'),
  ('220','country','Gambia','GM'),
  ('221','country','Senegal','SN'),
  ('222','country','Mauritania','MR'),
  ('223','country','Mali','ML'),
  ('224','country','Guinea','GN'),
  ('225','country','Cote d''Ivoire','CI'),
  ('226','country','Burkina Faso','BF'),
  ('227','country','Niger','NE'),
  ('228','country','Togo','TG'),
  ('229','country','Benin','BJ'),
  ('230','country','Mauritius','MU'),
  ('231','country','Liberia','LR'),
  ('232','country','Sierra Leone','SL'),
  ('233','country','Ghana','GH'),
  ('234','country','Nigeria','NG'),
  ('235','country','Chad','TD'),
  ('236','country','Central African Republic','CF'),
  ('237','country','Cameroon','CM'),
  ('238','country','Cape Verde','CV'),
  ('239','country','Sao Tome and Principe','ST'),
  ('240','country','Equatorial Guinea','GQ'),
  ('241','country','Gabon','GA'),
  ('242','country','Congo - Brazzaville','CG'),
  ('243','country','Congo - Kinshasa','CD'),
  ('244','country','Angola','AO'),
  ('245','country','Guinea-Bissau','GW'),
  ('246','country','British Indian Ocean Territory','IO'),
  ('248','country','Seychelles','SC'),
  ('249','country','Sudan','SD'),
  ('250','country','Rwanda','RW'),
  ('251','country','Ethiopia','ET'),
  ('252','country','Somalia','SO'),
  ('253','country','Djibouti','DJ'),
  ('254','country','Kenya','KE'),
  ('255','country','Tanzania','TZ'),
  ('256','country','Uganda','UG'),
  ('257','country','Burundi','BI'),
  ('258','country','Mozambique','MZ'),
  ('260','country','Zambia','ZM'),
  ('261','country','Madagascar','MG'),
  ('262','country','Reunion / Mayotte','RE'),
  ('263','country','Zimbabwe','ZW'),
  ('264','country','Namibia','NA'),
  ('265','country','Malawi','MW'),
  ('266','country','Lesotho','LS'),
  ('267','country','Botswana','BW'),
  ('268','country','Eswatini','SZ'),
  ('269','country','Comoros','KM'),
  ('290','country','Saint Helena','SH'),
  ('291','country','Eritrea','ER'),
  ('297','country','Aruba','AW'),
  ('298','country','Faroe Islands','FO'),
  ('299','country','Greenland','GL'),
  ('350','country','Gibraltar','GI'),
  ('351','country','Portugal','PT'),
  ('352','country','Luxembourg','LU'),
  ('353','country','Ireland','IE'),
  ('354','country','Iceland','IS'),
  ('355','country','Albania','AL'),
  ('356','country','Malta','MT'),
  ('357','country','Cyprus','CY'),
  ('358','country','Finland','FI'),
  ('359','country','Bulgaria','BG'),
  ('370','country','Lithuania','LT'),
  ('371','country','Latvia','LV'),
  ('372','country','Estonia','EE'),
  ('373','country','Moldova','MD'),
  ('374','country','Armenia','AM'),
  ('375','country','Belarus','BY'),
  ('376','country','Andorra','AD'),
  ('377','country','Monaco','MC'),
  ('378','country','San Marino','SM'),
  ('380','country','Ukraine','UA'),
  ('381','country','Serbia','RS'),
  ('382','country','Montenegro','ME'),
  ('383','country','Kosovo','XK'),
  ('385','country','Croatia','HR'),
  ('386','country','Slovenia','SI'),
  ('387','country','Bosnia and Herzegovina','BA'),
  ('389','country','North Macedonia','MK'),
  ('420','country','Czechia','CZ'),
  ('421','country','Slovakia','SK'),
  ('423','country','Liechtenstein','LI'),
  ('500','country','Falkland Islands','FK'),
  ('501','country','Belize','BZ'),
  ('502','country','Guatemala','GT'),
  ('503','country','El Salvador','SV'),
  ('504','country','Honduras','HN'),
  ('505','country','Nicaragua','NI'),
  ('506','country','Costa Rica','CR'),
  ('507','country','Panama','PA'),
  ('508','country','Saint Pierre and Miquelon','PM'),
  ('509','country','Haiti','HT'),
  ('590','country','Guadeloupe / Saint Martin','GP'),
  ('591','country','Bolivia','BO'),
  ('592','country','Guyana','GY'),
  ('593','country','Ecuador','EC'),
  ('594','country','French Guiana','GF'),
  ('595','country','Paraguay','PY'),
  ('596','country','Martinique','MQ'),
  ('597','country','Suriname','SR'),
  ('598','country','Uruguay','UY'),
  ('599','country','Curacao / Caribbean Netherlands','CW'),
  ('670','country','Timor-Leste','TL'),
  ('673','country','Brunei','BN'),
  ('674','country','Nauru','NR'),
  ('675','country','Papua New Guinea','PG'),
  ('676','country','Tonga','TO'),
  ('677','country','Solomon Islands','SB'),
  ('678','country','Vanuatu','VU'),
  ('679','country','Fiji','FJ'),
  ('680','country','Palau','PW'),
  ('681','country','Wallis and Futuna','WF'),
  ('682','country','Cook Islands','CK'),
  ('683','country','Niue','NU'),
  ('685','country','Samoa','WS'),
  ('686','country','Kiribati','KI'),
  ('687','country','New Caledonia','NC'),
  ('688','country','Tuvalu','TV'),
  ('689','country','French Polynesia','PF'),
  ('690','country','Tokelau','TK'),
  ('691','country','Micronesia','FM'),
  ('692','country','Marshall Islands','MH'),
  ('850','country','North Korea','KP'),
  ('852','country','Hong Kong','HK'),
  ('853','country','Macau','MO'),
  ('855','country','Cambodia','KH'),
  ('856','country','Laos','LA'),
  ('880','country','Bangladesh','BD'),
  ('886','country','Taiwan','TW'),
  ('960','country','Maldives','MV'),
  ('961','country','Lebanon','LB'),
  ('962','country','Jordan','JO'),
  ('963','country','Syria','SY'),
  ('964','country','Iraq','IQ'),
  ('965','country','Kuwait','KW'),
  ('966','country','Saudi Arabia','SA'),
  ('967','country','Yemen','YE'),
  ('968','country','Oman','OM'),
  ('970','country','Palestine','PS'),
  ('971','country','United Arab Emirates','AE'),
  ('972','country','Israel','IL'),
  ('973','country','Bahrain','BH'),
  ('974','country','Qatar','QA'),
  ('975','country','Bhutan','BT'),
  ('976','country','Mongolia','MN'),
  ('977','country','Nepal','NP'),
  ('992','country','Tajikistan','TJ'),
  ('993','country','Turkmenistan','TM'),
  ('994','country','Azerbaijan','AZ'),
  ('995','country','Georgia','GE'),
  ('996','country','Kyrgyzstan','KG'),
  ('998','country','Uzbekistan','UZ');

-- '1' is the whole North American Numbering Plan, which is 25 countries sharing
-- one country code. Blocking it wholesale is almost never what someone wants,
-- so it is listed for completeness and the picker warns on it.
insert into dial_prefixes (prefix, kind, name, region) values
  ('1','country','United States / Canada / NANP','US');

-- The non-US/Canada members of +1. These behave like country codes even though
-- they are dialled as area codes, and they are the ones a subscriber usually
-- means when they say "block that Caribbean number".
insert into dial_prefixes (prefix, kind, name, region) values
  ('1242','country','Bahamas','BS'),
  ('1246','country','Barbados','BB'),
  ('1264','country','Anguilla','AI'),
  ('1268','country','Antigua and Barbuda','AG'),
  ('1284','country','British Virgin Islands','VG'),
  ('1340','country','U.S. Virgin Islands','VI'),
  ('1345','country','Cayman Islands','KY'),
  ('1441','country','Bermuda','BM'),
  ('1473','country','Grenada','GD'),
  ('1649','country','Turks and Caicos Islands','TC'),
  ('1658','country','Jamaica','JM'),
  ('1664','country','Montserrat','MS'),
  ('1670','country','Northern Mariana Islands','MP'),
  ('1671','country','Guam','GU'),
  ('1684','country','American Samoa','AS'),
  ('1721','country','Sint Maarten','SX'),
  ('1758','country','Saint Lucia','LC'),
  ('1767','country','Dominica','DM'),
  ('1784','country','Saint Vincent and the Grenadines','VC'),
  ('1787','country','Puerto Rico','PR'),
  ('1809','country','Dominican Republic','DO'),
  ('1829','country','Dominican Republic','DO'),
  ('1849','country','Dominican Republic','DO'),
  ('1868','country','Trinidad and Tobago','TT'),
  ('1869','country','Saint Kitts and Nevis','KN'),
  ('1876','country','Jamaica','JM'),
  ('1939','country','Puerto Rico','PR');
