-- 0004_nanp_area_codes.sql — US and Canadian area codes for the rule picker.
--
-- Stored as the dialled prefix, so the 917 area code is the row '1917': a NANP
-- number is 1 + NPA + 7 digits, which makes an area code nothing more than a
-- longer country prefix and lets one matcher handle both.
--
-- Rows already claimed by 0003 (the Caribbean +1 members, which are countries
-- rather than area codes) are left alone.

set search_path = public;

insert into dial_prefixes (prefix, kind, name, region)
select '1' || npa, 'nanp_area', name, region
  from (values
    ('205','Alabama','US-AL'),('251','Alabama','US-AL'),('256','Alabama','US-AL'),
    ('334','Alabama','US-AL'),('659','Alabama','US-AL'),('938','Alabama','US-AL'),
    ('907','Alaska','US-AK'),
    ('480','Arizona','US-AZ'),('520','Arizona','US-AZ'),('602','Arizona','US-AZ'),
    ('623','Arizona','US-AZ'),('928','Arizona','US-AZ'),
    ('327','Arkansas','US-AR'),('479','Arkansas','US-AR'),('501','Arkansas','US-AR'),
    ('870','Arkansas','US-AR'),
    ('209','California','US-CA'),('213','California','US-CA'),('279','California','US-CA'),
    ('310','California','US-CA'),('323','California','US-CA'),('341','California','US-CA'),
    ('350','California','US-CA'),('408','California','US-CA'),('415','California','US-CA'),
    ('424','California','US-CA'),('442','California','US-CA'),('510','California','US-CA'),
    ('530','California','US-CA'),('559','California','US-CA'),('562','California','US-CA'),
    ('619','California','US-CA'),('626','California','US-CA'),('628','California','US-CA'),
    ('650','California','US-CA'),('657','California','US-CA'),('661','California','US-CA'),
    ('669','California','US-CA'),('707','California','US-CA'),('714','California','US-CA'),
    ('747','California','US-CA'),('760','California','US-CA'),('805','California','US-CA'),
    ('818','California','US-CA'),('820','California','US-CA'),('831','California','US-CA'),
    ('840','California','US-CA'),('858','California','US-CA'),('909','California','US-CA'),
    ('916','California','US-CA'),('925','California','US-CA'),('949','California','US-CA'),
    ('951','California','US-CA'),
    ('303','Colorado','US-CO'),('719','Colorado','US-CO'),('720','Colorado','US-CO'),
    ('970','Colorado','US-CO'),('983','Colorado','US-CO'),
    ('203','Connecticut','US-CT'),('475','Connecticut','US-CT'),('860','Connecticut','US-CT'),
    ('959','Connecticut','US-CT'),
    ('302','Delaware','US-DE'),
    ('202','District of Columbia','US-DC'),
    ('239','Florida','US-FL'),('305','Florida','US-FL'),('321','Florida','US-FL'),
    ('324','Florida','US-FL'),('352','Florida','US-FL'),('386','Florida','US-FL'),
    ('407','Florida','US-FL'),('448','Florida','US-FL'),('561','Florida','US-FL'),
    ('656','Florida','US-FL'),('689','Florida','US-FL'),('727','Florida','US-FL'),
    ('754','Florida','US-FL'),('772','Florida','US-FL'),('786','Florida','US-FL'),
    ('813','Florida','US-FL'),('850','Florida','US-FL'),('863','Florida','US-FL'),
    ('904','Florida','US-FL'),('941','Florida','US-FL'),('954','Florida','US-FL'),
    ('229','Georgia','US-GA'),('404','Georgia','US-GA'),('470','Georgia','US-GA'),
    ('478','Georgia','US-GA'),('678','Georgia','US-GA'),('706','Georgia','US-GA'),
    ('762','Georgia','US-GA'),('770','Georgia','US-GA'),('912','Georgia','US-GA'),
    ('943','Georgia','US-GA'),
    ('808','Hawaii','US-HI'),
    ('208','Idaho','US-ID'),('986','Idaho','US-ID'),
    ('217','Illinois','US-IL'),('224','Illinois','US-IL'),('309','Illinois','US-IL'),
    ('312','Illinois','US-IL'),('331','Illinois','US-IL'),('447','Illinois','US-IL'),
    ('464','Illinois','US-IL'),('618','Illinois','US-IL'),('630','Illinois','US-IL'),
    ('708','Illinois','US-IL'),('730','Illinois','US-IL'),('773','Illinois','US-IL'),
    ('779','Illinois','US-IL'),('815','Illinois','US-IL'),('847','Illinois','US-IL'),
    ('872','Illinois','US-IL'),
    ('219','Indiana','US-IN'),('260','Indiana','US-IN'),('317','Indiana','US-IN'),
    ('463','Indiana','US-IN'),('574','Indiana','US-IN'),('765','Indiana','US-IN'),
    ('812','Indiana','US-IN'),('930','Indiana','US-IN'),
    ('319','Iowa','US-IA'),('515','Iowa','US-IA'),('563','Iowa','US-IA'),
    ('641','Iowa','US-IA'),('712','Iowa','US-IA'),
    ('316','Kansas','US-KS'),('620','Kansas','US-KS'),('785','Kansas','US-KS'),
    ('913','Kansas','US-KS'),
    ('270','Kentucky','US-KY'),('364','Kentucky','US-KY'),('502','Kentucky','US-KY'),
    ('606','Kentucky','US-KY'),('859','Kentucky','US-KY'),
    ('225','Louisiana','US-LA'),('318','Louisiana','US-LA'),('337','Louisiana','US-LA'),
    ('504','Louisiana','US-LA'),('985','Louisiana','US-LA'),
    ('207','Maine','US-ME'),
    ('227','Maryland','US-MD'),('240','Maryland','US-MD'),('301','Maryland','US-MD'),
    ('410','Maryland','US-MD'),('443','Maryland','US-MD'),('667','Maryland','US-MD'),
    ('339','Massachusetts','US-MA'),('351','Massachusetts','US-MA'),('413','Massachusetts','US-MA'),
    ('508','Massachusetts','US-MA'),('617','Massachusetts','US-MA'),('774','Massachusetts','US-MA'),
    ('781','Massachusetts','US-MA'),('857','Massachusetts','US-MA'),('978','Massachusetts','US-MA'),
    ('231','Michigan','US-MI'),('248','Michigan','US-MI'),('269','Michigan','US-MI'),
    ('313','Michigan','US-MI'),('517','Michigan','US-MI'),('586','Michigan','US-MI'),
    ('616','Michigan','US-MI'),('679','Michigan','US-MI'),('734','Michigan','US-MI'),
    ('810','Michigan','US-MI'),('906','Michigan','US-MI'),('947','Michigan','US-MI'),
    ('989','Michigan','US-MI'),
    ('218','Minnesota','US-MN'),('320','Minnesota','US-MN'),('507','Minnesota','US-MN'),
    ('612','Minnesota','US-MN'),('651','Minnesota','US-MN'),('763','Minnesota','US-MN'),
    ('952','Minnesota','US-MN'),
    ('228','Mississippi','US-MS'),('601','Mississippi','US-MS'),('662','Mississippi','US-MS'),
    ('769','Mississippi','US-MS'),
    ('235','Missouri','US-MO'),('314','Missouri','US-MO'),('417','Missouri','US-MO'),
    ('557','Missouri','US-MO'),('573','Missouri','US-MO'),('636','Missouri','US-MO'),
    ('660','Missouri','US-MO'),('816','Missouri','US-MO'),
    ('406','Montana','US-MT'),
    ('308','Nebraska','US-NE'),('402','Nebraska','US-NE'),('531','Nebraska','US-NE'),
    ('702','Nevada','US-NV'),('725','Nevada','US-NV'),('775','Nevada','US-NV'),
    ('603','New Hampshire','US-NH'),
    ('201','New Jersey','US-NJ'),('551','New Jersey','US-NJ'),('609','New Jersey','US-NJ'),
    ('640','New Jersey','US-NJ'),('732','New Jersey','US-NJ'),('848','New Jersey','US-NJ'),
    ('856','New Jersey','US-NJ'),('862','New Jersey','US-NJ'),('908','New Jersey','US-NJ'),
    ('973','New Jersey','US-NJ'),
    ('505','New Mexico','US-NM'),('575','New Mexico','US-NM'),
    ('212','New York','US-NY'),('315','New York','US-NY'),('329','New York','US-NY'),
    ('332','New York','US-NY'),('347','New York','US-NY'),('363','New York','US-NY'),
    ('516','New York','US-NY'),('518','New York','US-NY'),('585','New York','US-NY'),
    ('607','New York','US-NY'),('631','New York','US-NY'),('646','New York','US-NY'),
    ('680','New York','US-NY'),('716','New York','US-NY'),('718','New York','US-NY'),
    ('838','New York','US-NY'),('845','New York','US-NY'),('914','New York','US-NY'),
    ('917','New York','US-NY'),('929','New York','US-NY'),('934','New York','US-NY'),
    ('252','North Carolina','US-NC'),('336','North Carolina','US-NC'),('704','North Carolina','US-NC'),
    ('743','North Carolina','US-NC'),('828','North Carolina','US-NC'),('910','North Carolina','US-NC'),
    ('919','North Carolina','US-NC'),('980','North Carolina','US-NC'),('984','North Carolina','US-NC'),
    ('701','North Dakota','US-ND'),
    ('216','Ohio','US-OH'),('220','Ohio','US-OH'),('234','Ohio','US-OH'),
    ('326','Ohio','US-OH'),('330','Ohio','US-OH'),('380','Ohio','US-OH'),
    ('419','Ohio','US-OH'),('436','Ohio','US-OH'),('440','Ohio','US-OH'),
    ('513','Ohio','US-OH'),('567','Ohio','US-OH'),('614','Ohio','US-OH'),
    ('740','Ohio','US-OH'),('937','Ohio','US-OH'),
    ('405','Oklahoma','US-OK'),('539','Oklahoma','US-OK'),('572','Oklahoma','US-OK'),
    ('580','Oklahoma','US-OK'),('918','Oklahoma','US-OK'),
    ('458','Oregon','US-OR'),('503','Oregon','US-OR'),('541','Oregon','US-OR'),
    ('971','Oregon','US-OR'),
    ('215','Pennsylvania','US-PA'),('223','Pennsylvania','US-PA'),('267','Pennsylvania','US-PA'),
    ('272','Pennsylvania','US-PA'),('412','Pennsylvania','US-PA'),('445','Pennsylvania','US-PA'),
    ('484','Pennsylvania','US-PA'),('570','Pennsylvania','US-PA'),('582','Pennsylvania','US-PA'),
    ('610','Pennsylvania','US-PA'),('717','Pennsylvania','US-PA'),('724','Pennsylvania','US-PA'),
    ('814','Pennsylvania','US-PA'),('835','Pennsylvania','US-PA'),('878','Pennsylvania','US-PA'),
    ('401','Rhode Island','US-RI'),
    ('803','South Carolina','US-SC'),('839','South Carolina','US-SC'),('843','South Carolina','US-SC'),
    ('854','South Carolina','US-SC'),('864','South Carolina','US-SC'),
    ('605','South Dakota','US-SD'),
    ('423','Tennessee','US-TN'),('615','Tennessee','US-TN'),('629','Tennessee','US-TN'),
    ('731','Tennessee','US-TN'),('865','Tennessee','US-TN'),('901','Tennessee','US-TN'),
    ('931','Tennessee','US-TN'),
    ('210','Texas','US-TX'),('214','Texas','US-TX'),('254','Texas','US-TX'),
    ('281','Texas','US-TX'),('325','Texas','US-TX'),('346','Texas','US-TX'),
    ('361','Texas','US-TX'),('409','Texas','US-TX'),('430','Texas','US-TX'),
    ('432','Texas','US-TX'),('469','Texas','US-TX'),('512','Texas','US-TX'),
    ('682','Texas','US-TX'),('713','Texas','US-TX'),('726','Texas','US-TX'),
    ('737','Texas','US-TX'),('806','Texas','US-TX'),('817','Texas','US-TX'),
    ('830','Texas','US-TX'),('832','Texas','US-TX'),('903','Texas','US-TX'),
    ('915','Texas','US-TX'),('936','Texas','US-TX'),('940','Texas','US-TX'),
    ('945','Texas','US-TX'),('956','Texas','US-TX'),('972','Texas','US-TX'),
    ('979','Texas','US-TX'),
    ('385','Utah','US-UT'),('435','Utah','US-UT'),('801','Utah','US-UT'),
    ('802','Vermont','US-VT'),
    ('276','Virginia','US-VA'),('434','Virginia','US-VA'),('540','Virginia','US-VA'),
    ('571','Virginia','US-VA'),('703','Virginia','US-VA'),('757','Virginia','US-VA'),
    ('804','Virginia','US-VA'),('826','Virginia','US-VA'),('948','Virginia','US-VA'),
    ('206','Washington','US-WA'),('253','Washington','US-WA'),('360','Washington','US-WA'),
    ('425','Washington','US-WA'),('509','Washington','US-WA'),('564','Washington','US-WA'),
    ('304','West Virginia','US-WV'),('681','West Virginia','US-WV'),
    ('262','Wisconsin','US-WI'),('274','Wisconsin','US-WI'),('414','Wisconsin','US-WI'),
    ('534','Wisconsin','US-WI'),('608','Wisconsin','US-WI'),('715','Wisconsin','US-WI'),
    ('920','Wisconsin','US-WI'),
    ('307','Wyoming','US-WY'),

    ('368','Alberta','CA-AB'),('403','Alberta','CA-AB'),('587','Alberta','CA-AB'),
    ('780','Alberta','CA-AB'),('825','Alberta','CA-AB'),
    ('236','British Columbia','CA-BC'),('250','British Columbia','CA-BC'),('257','British Columbia','CA-BC'),
    ('604','British Columbia','CA-BC'),('672','British Columbia','CA-BC'),('778','British Columbia','CA-BC'),
    ('204','Manitoba','CA-MB'),('431','Manitoba','CA-MB'),('584','Manitoba','CA-MB'),
    ('428','New Brunswick','CA-NB'),('506','New Brunswick','CA-NB'),
    ('709','Newfoundland and Labrador','CA-NL'),('879','Newfoundland and Labrador','CA-NL'),
    ('782','Nova Scotia / PEI','CA-NS'),('902','Nova Scotia / PEI','CA-NS'),
    ('226','Ontario','CA-ON'),('249','Ontario','CA-ON'),('289','Ontario','CA-ON'),
    ('343','Ontario','CA-ON'),('365','Ontario','CA-ON'),('382','Ontario','CA-ON'),
    ('416','Ontario','CA-ON'),('437','Ontario','CA-ON'),('519','Ontario','CA-ON'),
    ('548','Ontario','CA-ON'),('613','Ontario','CA-ON'),('647','Ontario','CA-ON'),
    ('683','Ontario','CA-ON'),('705','Ontario','CA-ON'),('742','Ontario','CA-ON'),
    ('753','Ontario','CA-ON'),('807','Ontario','CA-ON'),('905','Ontario','CA-ON'),
    ('263','Quebec','CA-QC'),('354','Quebec','CA-QC'),('367','Quebec','CA-QC'),
    ('418','Quebec','CA-QC'),('438','Quebec','CA-QC'),('450','Quebec','CA-QC'),
    ('468','Quebec','CA-QC'),('514','Quebec','CA-QC'),('579','Quebec','CA-QC'),
    ('581','Quebec','CA-QC'),('819','Quebec','CA-QC'),('873','Quebec','CA-QC'),
    ('306','Saskatchewan','CA-SK'),('474','Saskatchewan','CA-SK'),('639','Saskatchewan','CA-SK'),
    ('867','Northwest Territories / Nunavut / Yukon','CA-NT'),

    ('800','Toll-free','NANP'),('833','Toll-free','NANP'),('844','Toll-free','NANP'),
    ('855','Toll-free','NANP'),('866','Toll-free','NANP'),('877','Toll-free','NANP'),
    ('888','Toll-free','NANP'),('900','Premium rate','NANP'),('710','US Government','US')
  ) as t(npa, name, region)
on conflict (prefix) do nothing;
